# Generated by Django 3.0.5 on 2020-04-07 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whiskey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('style', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('price', models.CharField(blank=True, max_length=10)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('places', models.ManyToManyField(to='core.Place')),
                ('tags', models.ManyToManyField(to='core.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
