# Generated by Django 3.0.5 on 2020-04-10 01:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_whiskey'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiskey',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.whiskey_image_file_path),
        ),
    ]
